apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "spywatcher.fullname" . }}-config
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "spywatcher.labels" . | nindent 4 }}
data:
  {{- range $key, $value := .Values.configMap.data }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
